# Makefile rules generated by CB
CC	= gcc
CFLAGS	= -Wall -g 
LDLIBS	= -lm
BUILD	= assemble bitwise emulate immediateInstructionProcessing RegisterInstructionProcessing

all:	$(BUILD)

clean:
	/bin/rm -f $(BUILD) *.o core a.out

RegisterInstructionProcessing:	RegisterInstructionProcessing.o bitwise.o emulate.o branchInstructions.o immediateInstructionProcessing.o
RegisterInstructionProcessing.o:	RegisterInstructionProcessing.c RegisterInstructionProcessing.h bitwise.h emulate.h
assemble:	assemble.o
assemble.o:	assemble.c
bitwise:	bitwise.o
bitwise.o:	bitwise.c bitwise.h
branchInstructions.o:	branchInstructions.c branchInstructions.h emulate.h
emulate:	emulate.o RegisterInstructionProcessing.o bitwise.o branchInstructions.o immediateInstructionProcessing.o
emulate.o:	emulate.c RegisterInstructionProcessing.h bitwise.h branchInstructions.h emulate.h immediateInstructionProcessing.h singleMTransfer.h
immediateInstructionProcessing:	immediateInstructionProcessing.o bitwise.o emulate.o RegisterInstructionProcessing.o branchInstructions.o
immediateInstructionProcessing.o:	immediateInstructionProcessing.c bitwise.h emulate.h immediateInstructionProcessing.h

